export type Company = {
  id: number;
  name: string;
  domain: string;
  industry: string;
  hq_country: string;
  revenue: number;
  employees: number;
  technologies: string[];
  office_locations: string[];
};

export const companies: Company[] = [
  
    // Original companies (1-20)
    {
      id: 1,
      name: "Innovate Inc.",
      domain: "innovate.com",
      industry: "Technology",
      hq_country: "USA",
      revenue: 120000000,
      employees: 1500,
      technologies: ["React", "Node.js", "AWS", "PostgreSQL", "Stripe"],
      office_locations: ["San Francisco", "New York", "London"]
    },
    {
      id: 2,
      name: "HealthWell",
      domain: "healthwell.io",
      industry: "Healthcare",
      hq_country: "Canada",
      revenue: 75000000,
      employees: 800,
      technologies: ["Angular", "Python", "Google Cloud", "MySQL", "Shopify"],
      office_locations: ["Toronto", "Vancouver"]
    },
    {
      id: 3,
      name: "FinSecure",
      domain: "finsecure.co",
      industry: "Finance",
      hq_country: "UK",
      revenue: 250000000,
      employees: 3000,
      technologies: ["Java", ".NET", "Azure", "SQL Server", "Intercom"],
      office_locations: ["London", "Manchester", "Edinburgh"]
    },
    {
      id: 4,
      name: "E-Shop World",
      domain: "eshopworld.net",
      industry: "E-commerce",
      hq_country: "Ireland",
      revenue: 55000000,
      employees: 600,
      technologies: ["Shopify", "React", "GraphQL", "Stripe", "Zendesk"],
      office_locations: ["Dublin", "Berlin"]
    },
    {
      id: 5,
      name: "TravelGo",
      domain: "travelgo.com",
      industry: "Travel",
      hq_country: "Australia",
      revenue: 30000000,
      employees: 350,
      technologies: ["Vue.js", "PHP", "AWS", "MongoDB"],
      office_locations: ["Sydney", "Melbourne"]
    },
    {
      id: 6,
      name: "AdOptimize",
      domain: "adoptimize.ai",
      industry: "Advertising",
      hq_country: "USA",
      revenue: 90000000,
      employees: 1100,
      technologies: ["Python", "TensorFlow", "Google Cloud", "BigQuery", "React"],
      office_locations: ["Austin", "Chicago"]
    },
    {
      id: 7,
      name: "GreenEnergy Solutions",
      domain: "greenenergy.sol",
      industry: "Energy",
      hq_country: "Germany",
      revenue: 150000000,
      employees: 2200,
      technologies: ["Python", "Java", "Azure", "IoT", "SQL Server"],
      office_locations: ["Berlin", "Munich", "Hamburg"]
    },
    {
      id: 8,
      name: "RealEstate Finder",
      domain: "realestatefinder.com",
      industry: "Real Estate",
      hq_country: "USA",
      revenue: 42000000,
      employees: 550,
      technologies: ["React", "Firebase", "Google Maps API", "Node.js"],
      office_locations: ["Miami", "Los Angeles"]
    },
    {
      id: 9,
      name: "CyberGuard",
      domain: "cyberguard.tech",
      industry: "Cybersecurity",
      hq_country: "Israel",
      revenue: 88000000,
      employees: 900,
      technologies: ["Python", "Go", "AWS", "Kubernetes", "Elasticsearch"],
      office_locations: ["Tel Aviv"]
    },
    {
      id: 10,
      name: "Gamer's Hub",
      domain: "gamershub.io",
      industry: "Gaming",
      hq_country: "Japan",
      revenue: 300000000,
      employees: 4000,
      technologies: ["C++", "Unreal Engine", "Unity", "AWS", "Node.js", "Stripe"],
      office_locations: ["Tokyo", "Kyoto", "Seattle"]
    },
    {
      id: 11,
      name: "UK Travel Co",
      domain: "uktravel.co.uk",
      industry: "Travel",
      hq_country: "UK",
      revenue: 22000000,
      employees: 250,
      technologies: ["Wordpress", "PHP", "MySQL", "jQuery"],
      office_locations: ["London"]
    },
    {
      id: 12,
      name: "Aussie Adverts",
      domain: "aussieads.com.au",
      industry: "Advertising",
      hq_country: "Australia",
      revenue: 15000000,
      employees: 150,
      technologies: ["Google Analytics", "Facebook Ads", "Wordpress"],
      office_locations: ["Perth"]
    },
    {
      id: 13,
      name: "DataDriven Inc.",
      domain: "datadriven.com",
      industry: "Technology",
      hq_country: "USA",
      revenue: 180000000,
      employees: 2000,
      technologies: ["Python", "Spark", "Hadoop", "Tableau", "AWS"],
      office_locations: ["Palo Alto", "Boston"]
    },
    {
      id: 14,
      name: "BioGenCorp",
      domain: "biogencorp.com",
      industry: "Biotechnology",
      hq_country: "USA",
      revenue: 450000000,
      employees: 5000,
      technologies: ["Python", "R", "Next-Generation Sequencing", "CRISPR"],
      office_locations: ["Cambridge", "San Diego"]
    },
    {
      id: 15,
      name: "RoboLogistics",
      domain: "robologistics.com",
      industry: "Logistics",
      hq_country: "Germany",
      revenue: 95000000,
      employees: 1200,
      technologies: ["C++", "ROS", "Python", "AWS"],
      office_locations: ["Stuttgart", "Dresden"]
    },
    {
      id: 16,
      name: "QuantumLeap",
      domain: "quantumleap.ai",
      industry: "Technology",
      hq_country: "Canada",
      revenue: 60000000,
      employees: 400,
      technologies: ["Python", "Qiskit", "Google Cloud", "TensorFlow"],
      office_locations: ["Waterloo", "Montreal"]
    },
    {
      id: 17,
      name: "EduVerse",
      domain: "eduverse.com",
      industry: "Education",
      hq_country: "UK",
      revenue: 35000000,
      employees: 500,
      technologies: ["React", "Node.js", "MongoDB", "WebRTC"],
      office_locations: ["London", "Bristol"]
    },
    {
      id: 18,
      name: "AgriTech Global",
      domain: "agritech.global",
      industry: "Agriculture",
      hq_country: "Netherlands",
      revenue: 80000000,
      employees: 900,
      technologies: ["IoT", "Python", "Azure", "React Native"],
      office_locations: ["Wageningen", "Eindhoven"]
    },
    {
      id: 19,
      name: "MediaStream",
      domain: "mediastream.com",
      industry: "Media",
      hq_country: "USA",
      revenue: 220000000,
      employees: 2500,
      technologies: ["React", "Node.js", "AWS", "FFmpeg", "Stripe"],
      office_locations: ["Los Angeles", "New York"]
    },
    {
      id: 20,
      name: "SpaceQuest",
      domain: "spacequest.com",
      industry: "Aerospace",
      hq_country: "USA",
      revenue: 1000000000,
      employees: 10000,
      technologies: ["C++", "Python", "MATLAB", "Simulink", "FPGA"],
      office_locations: ["Hawthorne", "Cape Canaveral"]
    },
    // Extended companies (21-550)
    {
      id: 21,
      name: "TechNova Solutions",
      domain: "technova.se",
      industry: "Technology",
      hq_country: "Sweden",
      revenue: 85000000,
      employees: 750,
      technologies: ["React", "TypeScript", "Azure", "PostgreSQL"],
      office_locations: ["Stockholm", "Gothenburg", "Malmö"]
    },
    {
      id: 22,
      name: "HealthCare Plus",
      domain: "healthcareplus.fr",
      industry: "Healthcare",
      hq_country: "France",
      revenue: 125000000,
      employees: 1800,
      technologies: ["Vue.js", "Python", "Docker", "MongoDB"],
      office_locations: ["Paris", "Lyon", "Marseille"]
    },
    {
      id: 23,
      name: "CryptoBank Ltd",
      domain: "cryptobank.ch",
      industry: "Finance",
      hq_country: "Switzerland",
      revenue: 320000000,
      employees: 2500,
      technologies: ["Java", "Spring", "PostgreSQL", "Redis"],
      office_locations: ["Zurich", "Geneva", "Basel"]
    },
    {
      id: 24,
      name: "Nordic E-commerce",
      domain: "nordicecom.no",
      industry: "E-commerce",
      hq_country: "Norway",
      revenue: 45000000,
      employees: 380,
      technologies: ["React", "Node.js", "Stripe", "MongoDB"],
      office_locations: ["Oslo", "Bergen", "Trondheim"]
    },
    {
      id: 25,
      name: "Siena Travel Agency",
      domain: "sienatravel.it",
      industry: "Travel",
      hq_country: "Italy",
      revenue: 38000000,
      employees: 420,
      technologies: ["Angular", "PHP", "MySQL", "Booking.com API"],
      office_locations: ["Rome", "Milan", "Florence"]
    },
    {
      id: 26,
      name: "Brazilian Innovation Hub",
      domain: "brazilinnovation.com.br",
      industry: "Technology",
      hq_country: "Brazil",
      revenue: 70000000,
      employees: 850,
      technologies: ["React", "Python", "AWS", "Redis"],
      office_locations: ["São Paulo", "Rio de Janeiro", "Brasília"]
    },
    {
      id: 27,
      name: "Indian Software Solutions",
      domain: "indiansoftware.in",
      industry: "Technology",
      hq_country: "India",
      revenue: 95000000,
      employees: 2200,
      technologies: ["Java", "Spring Boot", "MySQL", "AWS"],
      office_locations: ["Bangalore", "Mumbai", "Pune", "Chennai"]
    },
    {
      id: 28,
      name: "Korean Gaming Corp",
      domain: "koreangaming.kr",
      industry: "Gaming",
      hq_country: "South Korea",
      revenue: 180000000,
      employees: 1600,
      technologies: ["Unity", "C#", "PostgreSQL", "AWS"],
      office_locations: ["Seoul", "Busan", "Incheon"]
    },
    {
      id: 29,
      name: "Chinese E-commerce Giant",
      domain: "chinesecom.cn",
      industry: "E-commerce",
      hq_country: "China",
      revenue: 850000000,
      employees: 15000,
      technologies: ["Vue.js", "Node.js", "MongoDB", "Alibaba Cloud"],
      office_locations: ["Shanghai", "Beijing", "Shenzhen", "Hangzhou"]
    },
    {
      id: 30,
      name: "Mexican FinTech",
      domain: "mexfintech.mx",
      industry: "Finance",
      hq_country: "Mexico",
      revenue: 55000000,
      employees: 650,
      technologies: ["React", "Python", "PostgreSQL", "Stripe"],
      office_locations: ["Mexico City", "Guadalajara", "Monterrey"]
    },
    {
      id: 31,
      name: "Argentina AgTech",
      domain: "argagtech.ar",
      industry: "Agriculture",
      hq_country: "Argentina",
      revenue: 28000000,
      employees: 320,
      technologies: ["Python", "IoT", "AWS", "React"],
      office_locations: ["Buenos Aires", "Córdoba", "Rosario"]
    },
    {
      id: 32,
      name: "Polish Healthcare Systems",
      domain: "polishhealthcare.pl",
      industry: "Healthcare",
      hq_country: "Poland",
      revenue: 42000000,
      employees: 580,
      technologies: ["Angular", "Java", "PostgreSQL", "Docker"],
      office_locations: ["Warsaw", "Krakow", "Gdansk"]
    },
    {
      id: 33,
      name: "Czech Republic Tech",
      domain: "czechtech.cz",
      industry: "Technology",
      hq_country: "Czech Republic",
      revenue: 35000000,
      employees: 450,
      technologies: ["React", "Python", "AWS", "MongoDB"],
      office_locations: ["Prague", "Brno", "Ostrava"]
    },
    {
      id: 34,
      name: "Hungarian Software House",
      domain: "hungariansoft.hu",
      industry: "Technology",
      hq_country: "Hungary",
      revenue: 25000000,
      employees: 320,
      technologies: ["Vue.js", "PHP", "MySQL", "Docker"],
      office_locations: ["Budapest", "Debrecen", "Szeged"]
    },
    {
      id: 35,
      name: "Romanian Cybersecurity",
      domain: "romaniacyber.ro",
      industry: "Cybersecurity",
      hq_country: "Romania",
      revenue: 18000000,
      employees: 220,
      technologies: ["Python", "Go", "Kubernetes", "Elasticsearch"],
      office_locations: ["Bucharest", "Cluj-Napoca", "Timișoara"]
    },
    {
      id: 36,
      name: "Bulgarian Gaming Studios",
      domain: "bulgariangaming.bg",
      industry: "Gaming",
      hq_country: "Bulgaria",
      revenue: 12000000,
      employees: 180,
      technologies: ["Unity", "C#", "MongoDB", "AWS"],
      office_locations: ["Sofia", "Plovdiv", "Varna"]
    },
    {
      id: 37,
      name: "Croatian Tourism Tech",
      domain: "croatourismtech.hr",
      industry: "Travel",
      hq_country: "Croatia",
      revenue: 15000000,
      employees: 150,
      technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
      office_locations: ["Zagreb", "Split", "Rijeka"]
    },
    {
      id: 38,
      name: "Serbian Software Solutions",
      domain: "serbiansoft.rs",
      industry: "Technology",
      hq_country: "Serbia",
      revenue: 22000000,
      employees: 280,
      technologies: ["Angular", "Java", "MySQL", "AWS"],
      office_locations: ["Belgrade", "Novi Sad", "Niš"]
    },
    {
      id: 39,
      name: "Slovenian Green Tech",
      domain: "sloveniangreen.si",
      industry: "Energy",
      hq_country: "Slovenia",
      revenue: 30000000,
      employees: 350,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Ljubljana", "Maribor", "Celje"]
    },
    {
      id: 40,
      name: "Slovak IT Services",
      domain: "slovakit.sk",
      industry: "Technology",
      hq_country: "Slovakia",
      revenue: 20000000,
      employees: 250,
      technologies: ["React", "PHP", "MySQL", "Docker"],
      office_locations: ["Bratislava", "Košice", "Prešov"]
    },
    {
      id: 41,
      name: "Estonian FinTech",
      domain: "estonianfintech.ee",
      industry: "Finance",
      hq_country: "Estonia",
      revenue: 32000000,
      employees: 280,
      technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
      office_locations: ["Tallinn", "Tartu", "Narva"]
    },
    {
      id: 42,
      name: "Latvian E-commerce Hub",
      domain: "latvianecom.lv",
      industry: "E-commerce",
      hq_country: "Latvia",
      revenue: 18000000,
      employees: 200,
      technologies: ["Vue.js", "PHP", "MySQL", "Shopify"],
      office_locations: ["Riga", "Daugavpils", "Liepāja"]
    },
    {
      id: 43,
      name: "Lithuanian Tech Innovators",
      domain: "lithuaniantech.lt",
      industry: "Technology",
      hq_country: "Lithuania",
      revenue: 24000000,
      employees: 320,
      technologies: ["Angular", "Python", "AWS", "MongoDB"],
      office_locations: ["Vilnius", "Kaunas", "Klaipėda"]
    },
    {
      id: 44,
      name: "Finnish Gaming Solutions",
      domain: "finnishgaming.fi",
      industry: "Gaming",
      hq_country: "Finland",
      revenue: 65000000,
      employees: 550,
      technologies: ["Unity", "C++", "AWS", "PostgreSQL"],
      office_locations: ["Helsinki", "Tampere", "Turku"]
    },
    {
      id: 45,
      name: "Danish Clean Energy",
      domain: "danishclean.dk",
      industry: "Energy",
      hq_country: "Denmark",
      revenue: 110000000,
      employees: 1200,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Copenhagen", "Aarhus", "Odense"]
    },
    {
      id: 46,
      name: "Icelandic Data Centers",
      domain: "icelandicdata.is",
      industry: "Technology",
      hq_country: "Iceland",
      revenue: 35000000,
      employees: 180,
      technologies: ["Python", "Kubernetes", "AWS", "MongoDB"],
      office_locations: ["Reykjavik", "Akureyri"]
    },
    {
      id: 47,
      name: "Luxembourg Banking Tech",
      domain: "luxbanktech.lu",
      industry: "Finance",
      hq_country: "Luxembourg",
      revenue: 75000000,
      employees: 450,
      technologies: ["Java", ".NET", "SQL Server", "Azure"],
      office_locations: ["Luxembourg City", "Esch-sur-Alzette"]
    },
    {
      id: 48,
      name: "Belgian Logistics Platform",
      domain: "belgianlogistics.be",
      industry: "Logistics",
      hq_country: "Belgium",
      revenue: 62000000,
      employees: 720,
      technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
      office_locations: ["Brussels", "Antwerp", "Ghent"]
    },
    {
      id: 49,
      name: "Austrian Tourism Solutions",
      domain: "austriantourism.at",
      industry: "Travel",
      hq_country: "Austria",
      revenue: 28000000,
      employees: 320,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Vienna", "Salzburg", "Innsbruck"]
    },
    {
      id: 50,
      name: "Portuguese Maritime Tech",
      domain: "portmaritime.pt",
      industry: "Technology",
      hq_country: "Portugal",
      revenue: 40000000,
      employees: 480,
      technologies: ["React", "Python", "AWS", "PostgreSQL"],
      office_locations: ["Lisbon", "Porto", "Braga"]
    },
    {
      id: 51,
      name: "Spanish Renewable Energy",
      domain: "spanishrenewable.es",
      industry: "Energy",
      hq_country: "Spain",
      revenue: 155000000,
      employees: 1800,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Madrid", "Barcelona", "Valencia", "Seville"]
    },
    {
      id: 52,
      name: "Greek Shipping Solutions",
      domain: "greekshipping.gr",
      industry: "Logistics",
      hq_country: "Greece",
      revenue: 48000000,
      employees: 580,
      technologies: ["Java", "Spring", "MySQL", "Docker"],
      office_locations: ["Athens", "Thessaloniki", "Patras"]
    },
    {
      id: 53,
      name: "Turkish E-commerce Platform",
      domain: "turkishecom.tr",
      industry: "E-commerce",
      hq_country: "Turkey",
      revenue: 72000000,
      employees: 920,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Istanbul", "Ankara", "Izmir"]
    },
    {
      id: 54,
      name: "Russian Tech Giant",
      domain: "russiantech.ru",
      industry: "Technology",
      hq_country: "Russia",
      revenue: 280000000,
      employees: 3500,
      technologies: ["Python", "Java", "PostgreSQL", "Kubernetes"],
      office_locations: ["Moscow", "St. Petersburg", "Novosibirsk"]
    },
    {
      id: 55,
      name: "Ukrainian Software Development",
      domain: "ukrainiandev.ua",
      industry: "Technology",
      hq_country: "Ukraine",
      revenue: 45000000,
      employees: 650,
      technologies: ["React", "Python", "AWS", "PostgreSQL"],
      office_locations: ["Kyiv", "Kharkiv", "Odesa"]
    },
    {
      id: 56,
      name: "Belarusian IT Solutions",
      domain: "belarusianit.by",
      industry: "Technology",
      hq_country: "Belarus",
      revenue: 25000000,
      employees: 350,
      technologies: ["Angular", "Java", "MySQL", "Docker"],
      office_locations: ["Minsk", "Brest", "Gomel"]
    },
    {
      id: 57,
      name: "Moldovan AgriTech",
      domain: "moldovanagri.md",
      industry: "Agriculture",
      hq_country: "Moldova",
      revenue: 12000000,
      employees: 180,
      technologies: ["IoT", "Python", "AWS", "MongoDB"],
      office_locations: ["Chișinău", "Bălți"]
    },
    {
      id: 58,
      name: "Georgian Wine Tech",
      domain: "georgianwine.ge",
      industry: "Agriculture",
      hq_country: "Georgia",
      revenue: 15000000,
      employees: 120,
      technologies: ["React", "Node.js", "PostgreSQL", "IoT"],
      office_locations: ["Tbilisi", "Batumi", "Kutaisi"]
    },
    {
      id: 59,
      name: "Armenian Software House",
      domain: "armeniansoft.am",
      industry: "Technology",
      hq_country: "Armenia",
      revenue: 18000000,
      employees: 240,
      technologies: ["Vue.js", "Python", "MySQL", "Docker"],
      office_locations: ["Yerevan", "Gyumri", "Vanadzor"]
    },
    {
      id: 60,
      name: "Azerbaijani Energy Solutions",
      domain: "azerbaijanienergy.az",
      industry: "Energy",
      hq_country: "Azerbaijan",
      revenue: 85000000,
      employees: 950,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Baku", "Ganja", "Sumgayit"]
    },
    {
      id: 61,
      name: "Kazakhstan Mining Tech",
      domain: "kazakhmining.kz",
      industry: "Technology",
      hq_country: "Kazakhstan",
      revenue: 68000000,
      employees: 780,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Almaty", "Nur-Sultan", "Shymkent"]
    },
    {
      id: 62,
      name: "Uzbek Cotton Solutions",
      domain: "uzbekcotton.uz",
      industry: "Agriculture",
      hq_country: "Uzbekistan",
      revenue: 22000000,
      employees: 300,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Tashkent", "Samarkand", "Bukhara"]
    },
    {
      id: 63,
      name: "Kyrgyz Tech Startup",
      domain: "kyrgyztech.kg",
      industry: "Technology",
      hq_country: "Kyrgyzstan",
      revenue: 8000000,
      employees: 95,
      technologies: ["Vue.js", "Node.js", "MongoDB", "AWS"],
      office_locations: ["Bishkek", "Osh"]
    },
    {
      id: 64,
      name: "Tajik Software Solutions",
      domain: "tajiksoft.tj",
      industry: "Technology",
      hq_country: "Tajikistan",
      revenue: 6000000,
      employees: 75,
      technologies: ["React", "Python", "MySQL", "Docker"],
      office_locations: ["Dushanbe", "Khujand"]
    },
    {
      id: 65,
      name: "Turkmen Energy Corp",
      domain: "turkmenenergy.tm",
      industry: "Energy",
      hq_country: "Turkmenistan",
      revenue: 45000000,
      employees: 520,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Ashgabat", "Turkmenbashi"]
    },
    {
      id: 66,
      name: "Afghan Telecommunications",
      domain: "afghantel.af",
      industry: "Technology",
      hq_country: "Afghanistan",
      revenue: 25000000,
      employees: 380,
      technologies: ["Java", "Spring", "MySQL", "Docker"],
      office_locations: ["Kabul", "Herat", "Kandahar"]
    },
    {
      id: 67,
      name: "Pakistani Software House",
      domain: "pakistanisoft.pk",
      industry: "Technology",
      hq_country: "Pakistan",
      revenue: 38000000,
      employees: 580,
      technologies: ["React", "Node.js", "MongoDB", "AWS"],
      office_locations: ["Karachi", "Lahore", "Islamabad"]
    },
    {
      id: 68,
      name: "Bangladeshi Textile Tech",
      domain: "bangladeshitextile.bd",
      industry: "Manufacturing",
      hq_country: "Bangladesh",
      revenue: 32000000,
      employees: 1200,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Dhaka", "Chittagong", "Sylhet"]
    },
    {
      id: 69,
      name: "Sri Lankan Tourism Platform",
      domain: "srilankantourism.lk",
      industry: "Travel",
      hq_country: "Sri Lanka",
      revenue: 18000000,
      employees: 220,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Colombo", "Kandy", "Galle"]
    },
    {
      id: 70,
      name: "Maldivian Resort Tech",
      domain: "maldivianresort.mv",
      industry: "Travel",
      hq_country: "Maldives",
      revenue: 12000000,
      employees: 85,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Malé", "Addu City"]
    },
    {
      id: 71,
      name: "Nepalese Mountain Solutions",
      domain: "nepalesemountain.np",
      industry: "Travel",
      hq_country: "Nepal",
      revenue: 8000000,
      employees: 120,
      technologies: ["WordPress", "PHP", "MySQL", "Stripe"],
      office_locations: ["Kathmandu", "Pokhara", "Lalitpur"]
    },
    {
      id: 72,
      name: "Bhutanese Happiness Tech",
      domain: "bhutanesehappiness.bt",
      industry: "Technology",
      hq_country: "Bhutan",
      revenue: 5000000,
      employees: 65,
      technologies: ["React", "Python", "MongoDB", "AWS"],
      office_locations: ["Thimphu", "Phuentsholing"]
    },
    {
      id: 73,
      name: "Thai E-commerce Solutions",
      domain: "thaiecom.th",
      industry: "E-commerce",
      hq_country: "Thailand",
      revenue: 85000000,
      employees: 1100,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Bangkok", "Chiang Mai", "Phuket"]
    },
    {
      id: 74,
      name: "Vietnamese Software Factory",
      domain: "vietnamesesoft.vn",
      industry: "Technology",
      hq_country: "Vietnam",
      revenue: 52000000,
      employees: 850,
      technologies: ["Angular", "Java", "PostgreSQL", "AWS"],
      office_locations: ["Ho Chi Minh City", "Hanoi", "Da Nang"]
    },
    {
      id: 75,
      name: "Cambodian Agriculture Tech",
      domain: "cambodianagri.kh",
      industry: "Agriculture",
      hq_country: "Cambodia",
      revenue: 14000000,
      employees: 180,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Phnom Penh", "Siem Reap", "Battambang"]
    },
    {
      id: 76,
      name: "Laotian Tourism Platform",
      domain: "laotiantourism.la",
      industry: "Travel",
      hq_country: "Laos",
      revenue: 9000000,
      employees: 110,
      technologies: ["WordPress", "PHP", "MySQL", "Stripe"],
      office_locations: ["Vientiane", "Luang Prabang"]
    },
    {
      id: 77,
      name: "Myanmar Software Solutions",
      domain: "myanmarsoft.mm",
      industry: "Technology",
      hq_country: "Myanmar",
      revenue: 16000000,
      employees: 220,
      technologies: ["Angular", "Java", "MySQL", "AWS"],
      office_locations: ["Yangon", "Mandalay", "Naypyidaw"]
    },
    {
      id: 78,
      name: "Malaysian FinTech Hub",
      domain: "malaysianfintech.my",
      industry: "Finance",
      hq_country: "Malaysia",
      revenue: 68000000,
      employees: 850,
      technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
      office_locations: ["Kuala Lumpur", "George Town", "Johor Bahru"]
    },
    {
      id: 79,
      name: "Singapore AI Solutions",
      domain: "singaporeai.sg",
      industry: "Technology",
      hq_country: "Singapore",
      revenue: 125000000,
      employees: 950,
      technologies: ["Python", "TensorFlow", "AWS", "PostgreSQL"],
      office_locations: ["Singapore City"]
    },
    {
      id: 80,
      name: "Indonesian E-commerce Platform",
      domain: "indonesianecom.id",
      industry: "E-commerce",
      hq_country: "Indonesia",
      revenue: 95000000,
      employees: 1400,
      technologies: ["Vue.js", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Jakarta", "Surabaya", "Bandung", "Medan"]
    },
    {
      id: 81,
      name: "Philippine Software House",
      domain: "philippinesoft.ph",
      industry: "Technology",
      hq_country: "Philippines",
      revenue: 42000000,
      employees: 680,
      technologies: ["React", "Python", "MySQL", "AWS"],
      office_locations: ["Manila", "Cebu City", "Davao City"]
    },
    {
      id: 82,
      name: "Bruneian Energy Solutions",
      domain: "bruneienenergy.bn",
      industry: "Energy",
      hq_country: "Brunei",
      revenue: 35000000,
      employees: 280,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Bandar Seri Begawan", "Kuala Belait"]
    },
    {
      id: 83,
      name: "Mongolian Mining Tech",
      domain: "mongolianmining.mn",
      industry: "Technology",
      hq_country: "Mongolia",
      revenue: 28000000,
      employees: 320,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Ulaanbaatar", "Erdenet", "Darkhan"]
    },
    {
      id: 84,
      name: "North Korean Tech Solutions",
      domain: "nktech.kp",
      industry: "Technology",
      hq_country: "North Korea",
      revenue: 15000000,
      employees: 250,
      technologies: ["Java", "Python", "MySQL", "Docker"],
      office_locations: ["Pyongyang", "Nampo"]
    },
    {
      id: 85,
      name: "Iranian Software Development",
      domain: "iraniansoft.ir",
      industry: "Technology",
      hq_country: "Iran",
      revenue: 55000000,
      employees: 780,
      technologies: ["React", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Tehran", "Isfahan", "Mashhad", "Shiraz"]
    },
    {
      id: 86,
      name: "Iraqi Oil Tech Solutions",
      domain: "iraqioiltech.iq",
      industry: "Energy",
      hq_country: "Iraq",
      revenue: 48000000,
      employees: 580,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Baghdad", "Basra", "Erbil"]
    },
    {
      id: 87,
      name: "Syrian Software House",
      domain: "syriansoft.sy",
      industry: "Technology",
      hq_country: "Syria",
      revenue: 22000000,
      employees: 320,
      technologies: ["Angular", "Java", "MySQL", "Docker"],
      office_locations: ["Damascus", "Aleppo", "Homs"]
    },
    {
      id: 88,
      name: "Lebanese FinTech",
      domain: "lebanesefintech.lb",
      industry: "Finance",
      hq_country: "Lebanon",
      revenue: 35000000,
      employees: 420,
      technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
      office_locations: ["Beirut", "Tripoli", "Sidon"]
    },
    {
      id: 89,
      name: "Jordanian E-commerce Hub",
      domain: "jordanianecom.jo",
      industry: "E-commerce",
      hq_country: "Jordan",
      revenue: 28000000,
      employees: 350,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Amman", "Zarqa", "Irbid"]
    },
    {
      id: 90,
      name: "Saudi Arabian Tech Giants",
      domain: "sauditech.sa",
      industry: "Technology",
      hq_country: "Saudi Arabia",
      revenue: 185000000,
      employees: 2200,
      technologies: ["React", "Python", "AWS", "PostgreSQL"],
      office_locations: ["Riyadh", "Jeddah", "Dammam", "Mecca"]
    },
    {
      id: 91,
      name: "Kuwaiti Financial Solutions",
      domain: "kuwaitifinance.kw",
      industry: "Finance",
      hq_country: "Kuwait",
      revenue: 75000000,
      employees: 650,
      technologies: ["Java", "Spring", "PostgreSQL", "Azure"],
      office_locations: ["Kuwait City", "Hawalli", "Al Ahmadi"]
    },
    {
      id: 92,
      name: "Qatari Energy Tech",
      domain: "qatarienergy.qa",
      industry: "Energy",
      hq_country: "Qatar",
      revenue: 95000000,
      employees: 850,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Doha", "Al Rayyan", "Al Wakrah"]
    },
    {
      id: 93,
      name: "UAE Tech Hub",
      domain: "uaetech.ae",
      industry: "Technology",
      hq_country: "United Arab Emirates",
      revenue: 145000000,
      employees: 1250,
      technologies: ["React", "Python", "AWS", "MongoDB"],
      office_locations: ["Dubai", "Abu Dhabi", "Sharjah"]
    },
    {
      id: 94,
      name: "Omani Logistics Solutions",
      domain: "omanilogistics.om",
      industry: "Logistics",
      hq_country: "Oman",
      revenue: 42000000,
      employees: 480,
      technologies: ["Angular", "Java", "PostgreSQL", "Docker"],
      office_locations: ["Muscat", "Salalah", "Sohar"]
    },
    {
      id: 95,
      name: "Yemeni Agricultural Tech",
      domain: "yemeniagri.ye",
      industry: "Agriculture",
      hq_country: "Yemen",
      revenue: 8000000,
      employees: 120,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Sanaa", "Aden", "Taiz"]
    },
    {
      id: 96,
      name: "Bahraini Banking Solutions",
      domain: "bahrainbanking.bh",
      industry: "Finance",
      hq_country: "Bahrain",
      revenue: 52000000,
      employees: 420,
      technologies: ["Java", ".NET", "SQL Server", "Azure"],
      office_locations: ["Manama", "Muharraq", "Riffa"]
    },
    {
      id: 97,
      name: "Egyptian Tourism Platform",
      domain: "egyptiantourism.eg",
      industry: "Travel",
      hq_country: "Egypt",
      revenue: 48000000,
      employees: 620,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Cairo", "Alexandria", "Giza", "Luxor"]
    },
    {
      id: 98,
      name: "Libyan Oil Tech",
      domain: "libyanoiltech.ly",
      industry: "Energy",
      hq_country: "Libya",
      revenue: 65000000,
      employees: 580,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Tripoli", "Benghazi", "Misrata"]
    },
    {
      id: 99,
      name: "Tunisian Software Solutions",
      domain: "tunisiansoft.tn",
      industry: "Technology",
      hq_country: "Tunisia",
      revenue: 22000000,
      employees: 320,
      technologies: ["Vue.js", "Python", "MySQL", "Docker"],
      office_locations: ["Tunis", "Sfax", "Sousse"]
    },
    {
      id: 100,
      name: "Algerian Energy Corp",
      domain: "algerianenergy.dz",
      industry: "Energy",
      hq_country: "Algeria",
      revenue: 85000000,
      employees: 980,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Algiers", "Oran", "Constantine"]
    },
    {
      id: 101,
      name: "Moroccan Tech Innovations",
      domain: "moroccantech.ma",
      industry: "Technology",
      hq_country: "Morocco",
      revenue: 38000000,
      employees: 480,
      technologies: ["React", "Python", "AWS", "MongoDB"],
      office_locations: ["Casablanca", "Rabat", "Marrakech", "Fez"]
    },
    {
      id: 102,
      name: "South African Mining Solutions",
      domain: "southafricanmining.za",
      industry: "Technology",
      hq_country: "South Africa",
      revenue: 78000000,
      employees: 920,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Cape Town", "Johannesburg", "Durban", "Pretoria"]
    },
    {
      id: 103,
      name: "Nigerian FinTech Revolution",
      domain: "nigerianfintech.ng",
      industry: "Finance",
      hq_country: "Nigeria",
      revenue: 95000000,
      employees: 1200,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Lagos", "Abuja", "Port Harcourt", "Kano"]
    },
    {
      id: 104,
      name: "Kenyan Mobile Solutions",
      domain: "kenyanmobile.ke",
      industry: "Technology",
      hq_country: "Kenya",
      revenue: 45000000,
      employees: 580,
      technologies: ["React Native", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Nairobi", "Mombasa", "Kisumu"]
    },
    {
      id: 105,
      name: "Ethiopian Agricultural Platform",
      domain: "ethiopianagri.et",
      industry: "Agriculture",
      hq_country: "Ethiopia",
      revenue: 18000000,
      employees: 280,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Addis Ababa", "Dire Dawa", "Mekelle"]
    },
    {
      id: 106,
      name: "Ghanaian E-commerce Hub",
      domain: "ghanaianecom.gh",
      industry: "E-commerce",
      hq_country: "Ghana",
      revenue: 32000000,
      employees: 420,
      technologies: ["Vue.js", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Accra", "Kumasi", "Tamale"]
    },
    {
      id: 107,
      name: "Ivorian Tech Solutions",
      domain: "ivoriantech.ci",
      industry: "Technology",
      hq_country: "Ivory Coast",
      revenue: 28000000,
      employees: 380,
      technologies: ["Angular", "Java", "PostgreSQL", "Docker"],
      office_locations: ["Abidjan", "Bouaké", "Yamoussoukro"]
    },
    {
      id: 108,
      name: "Senegalese Software House",
      domain: "senegalesesoft.sn",
      industry: "Technology",
      hq_country: "Senegal",
      revenue: 22000000,
      employees: 320,
      technologies: ["React", "Python", "MySQL", "AWS"],
      office_locations: ["Dakar", "Thiès", "Kaolack"]
    },
    {
      id: 109,
      name: "Malian Agriculture Tech",
      domain: "malianagri.ml",
      industry: "Agriculture",
      hq_country: "Mali",
      revenue: 12000000,
      employees: 180,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Bamako", "Sikasso", "Mopti"]
    },
    {
      id: 110,
      name: "Burkina Faso Solar Solutions",
      domain: "burkinasolar.bf",
      industry: "Energy",
      hq_country: "Burkina Faso",
      revenue: 15000000,
      employees: 220,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Ouagadougou", "Bobo-Dioulasso"]
    },
    {
      id: 111,
      name: "Niger Mining Tech",
      domain: "nigermining.ne",
      industry: "Technology",
      hq_country: "Niger",
      revenue: 18000000,
      employees: 250,
      technologies: ["Java", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Niamey", "Zinder", "Maradi"]
    },
    {
      id: 112,
      name: "Chad Energy Solutions",
      domain: "chadenergy.td",
      industry: "Energy",
      hq_country: "Chad",
      revenue: 22000000,
      employees: 280,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["N'Djamena", "Moundou", "Sarh"]
    },
    {
      id: 113,
      name: "Sudanese Agricultural Platform",
      domain: "sudaneseagri.sd",
      industry: "Agriculture",
      hq_country: "Sudan",
      revenue: 25000000,
      employees: 380,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Khartoum", "Omdurman", "Port Sudan"]
    },
    {
      id: 114,
      name: "South Sudanese Oil Tech",
      domain: "southsudanoil.ss",
      industry: "Energy",
      hq_country: "South Sudan",
      revenue: 35000000,
      employees: 420,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Juba", "Malakal", "Wau"]
    },
    {
      id: 115,
      name: "Eritrean Mining Solutions",
      domain: "eritreanmining.er",
      industry: "Technology",
      hq_country: "Eritrea",
      revenue: 12000000,
      employees: 150,
      technologies: ["Java", "Python", "MySQL", "Docker"],
      office_locations: ["Asmara", "Massawa"]
    },
    {
      id: 116,
      name: "Djiboutian Logistics Hub",
      domain: "djiboutianlogistics.dj",
      industry: "Logistics",
      hq_country: "Djibouti",
      revenue: 18000000,
      employees: 220,
      technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
      office_locations: ["Djibouti City", "Ali Sabieh"]
    },
    {
      id: 117,
      name: "Somali Telecommunications",
      domain: "somalitel.so",
      industry: "Technology",
      hq_country: "Somalia",
      revenue: 15000000,
      employees: 200,
      technologies: ["Angular", "Java", "MySQL", "AWS"],
      office_locations: ["Mogadishu", "Hargeisa", "Bosaso"]
    },
    {
      id: 118,
      name: "Ugandan Mobile Banking",
      domain: "ugandanmobile.ug",
      industry: "Finance",
      hq_country: "Uganda",
      revenue: 32000000,
      employees: 450,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Kampala", "Gulu", "Mbarara"]
    },
    {
      id: 119,
      name: "Rwandan Tech Innovation",
      domain: "rwandantech.rw",
      industry: "Technology",
      hq_country: "Rwanda",
      revenue: 25000000,
      employees: 320,
      technologies: ["React", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Kigali", "Butare", "Gitarama"]
    },
    {
      id: 120,
      name: "Burundian Agriculture Solutions",
      domain: "burundianagri.bi",
      industry: "Agriculture",
      hq_country: "Burundi",
      revenue: 8000000,
      employees: 120,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Gitega", "Bujumbura"]
    },
    {
      id: 121,
      name: "Tanzanian Safari Tech",
      domain: "tanzaniansafari.tz",
      industry: "Travel",
      hq_country: "Tanzania",
      revenue: 22000000,
      employees: 280,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Dar es Salaam", "Arusha", "Mwanza"]
    },
    {
      id: 122,
      name: "Congolese Mining Platform",
      domain: "congolesemining.cd",
      industry: "Technology",
      hq_country: "Democratic Republic of Congo",
      revenue: 35000000,
      employees: 480,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"]
    },
    {
      id: 123,
      name: "Central African Republic Tech",
      domain: "cartech.cf",
      industry: "Technology",
      hq_country: "Central African Republic",
      revenue: 5000000,
      employees: 65,
      technologies: ["React", "Python", "MySQL", "Docker"],
      office_locations: ["Bangui", "Berbérati"]
    },
    {
      id: 124,
      name: "Cameroonian Software Solutions",
      domain: "camerooniansoft.cm",
      industry: "Technology",
      hq_country: "Cameroon",
      revenue: 28000000,
      employees: 380,
      technologies: ["Angular", "Java", "PostgreSQL", "Docker"],
      office_locations: ["Yaoundé", "Douala", "Bamenda"]
    },
    {
      id: 125,
      name: "Equatorial Guinean Oil Tech",
      domain: "equatorialguineanoil.gq",
      industry: "Energy",
      hq_country: "Equatorial Guinea",
      revenue: 45000000,
      employees: 320,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Malabo", "Bata"]
    },
    {
      id: 126,
      name: "Gabonese Forestry Solutions",
      domain: "gaboneseforestry.ga",
      industry: "Agriculture",
      hq_country: "Gabon",
      revenue: 18000000,
      employees: 220,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Libreville", "Port-Gentil", "Franceville"]
    },
    {
      id: 127,
      name: "Republic of Congo Tech",
      domain: "congotech.cg",
      industry: "Technology",
      hq_country: "Republic of Congo",
      revenue: 15000000,
      employees: 180,
      technologies: ["Vue.js", "PHP", "MySQL", "AWS"],
      office_locations: ["Brazzaville", "Pointe-Noire"]
    },
    {
      id: 128,
      name: "Angolan Diamond Tech",
      domain: "angolandiamondtech.ao",
      industry: "Technology",
      hq_country: "Angola",
      revenue: 42000000,
      employees: 520,
      technologies: ["Java", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Luanda", "Huambo", "Lubango"]
    },
    {
      id: 129,
      name: "Zambian Copper Solutions",
      domain: "zambiancopper.zm",
      industry: "Technology",
      hq_country: "Zambia",
      revenue: 28000000,
      employees: 350,
      technologies: ["React", "Python", "MySQL", "AWS"],
      office_locations: ["Lusaka", "Ndola", "Kitwe"]
    },
    {
      id: 130,
      name: "Zimbabwean Agricultural Platform",
      domain: "zimbabweanagri.zw",
      industry: "Agriculture",
      hq_country: "Zimbabwe",
      revenue: 18000000,
      employees: 250,
      technologies: ["Angular", "Java", "MySQL", "IoT"],
      office_locations: ["Harare", "Bulawayo", "Mutare"]
    },
    {
      id: 131,
      name: "Botswanan Diamond Tech",
      domain: "botswanandiamond.bw",
      industry: "Technology",
      hq_country: "Botswana",
      revenue: 35000000,
      employees: 280,
      technologies: ["React", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Gaborone", "Francistown"]
    },
    {
      id: 132,
      name: "Namibian Mining Solutions",
      domain: "namibianmining.na",
      industry: "Technology",
      hq_country: "Namibia",
      revenue: 25000000,
      employees: 220,
      technologies: ["Java", "Python", "MySQL", "Docker"],
      office_locations: ["Windhoek", "Walvis Bay"]
    },
    {
      id: 133,
      name: "Swazi Agricultural Tech",
      domain: "swaziagri.sz",
      industry: "Agriculture",
      hq_country: "Eswatini",
      revenue: 12000000,
      employees: 150,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Mbabane", "Manzini"]
    },
    {
      id: 134,
      name: "Lesotho Software Solutions",
      domain: "lesothosoft.ls",
      industry: "Technology",
      hq_country: "Lesotho",
      revenue: 8000000,
      employees: 95,
      technologies: ["Vue.js", "Python", "MongoDB", "AWS"],
      office_locations: ["Maseru", "Teyateyaneng"]
    },
    {
      id: 135,
      name: "Malawian Healthcare Tech",
      domain: "malawianhealthcare.mw",
      industry: "Healthcare",
      hq_country: "Malawi",
      revenue: 15000000,
      employees: 200,
      technologies: ["React", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Lilongwe", "Blantyre", "Mzuzu"]
    },
    {
      id: 136,
      name: "Mozambican Port Solutions",
      domain: "mozambicanport.mz",
      industry: "Logistics",
      hq_country: "Mozambique",
      revenue: 28000000,
      employees: 380,
      technologies: ["Angular", "Java", "MySQL", "Docker"],
      office_locations: ["Maputo", "Beira", "Nampula"]
    },
    {
      id: 137,
      name: "Madagascan Vanilla Tech",
      domain: "madagascanvanilla.mg",
      industry: "Agriculture",
      hq_country: "Madagascar",
      revenue: 18000000,
      employees: 250,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Antananarivo", "Toamasina", "Antsirabe"]
    },
    {
      id: 138,
      name: "Mauritian Tourism Platform",
      domain: "mauritiantourism.mu",
      industry: "Travel",
      hq_country: "Mauritius",
      revenue: 32000000,
      employees: 280,
      technologies: ["Vue.js", "PHP", "PostgreSQL", "Stripe"],
      office_locations: ["Port Louis", "Beau Bassin-Rose Hill"]
    },
    {
      id: 139,
      name: "Seychellois Resort Tech",
      domain: "seychelloisresort.sc",
      industry: "Travel",
      hq_country: "Seychelles",
      revenue: 25000000,
      employees: 120,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Victoria", "Praslin"]
    },
    {
      id: 140,
      name: "Comorian Maritime Solutions",
      domain: "comorianmaritime.km",
      industry: "Logistics",
      hq_country: "Comoros",
      revenue: 8000000,
      employees: 85,
      technologies: ["React", "PHP", "MySQL", "Docker"],
      office_locations: ["Moroni", "Mutsamudu"]
    },
    {
      id: 141,
      name: "Cape Verdean Wind Energy",
      domain: "capeverdeanwind.cv",
      industry: "Energy",
      hq_country: "Cape Verde",
      revenue: 15000000,
      employees: 150,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Praia", "Mindelo"]
    },
    {
      id: 142,
      name: "Guinean Mining Platform",
      domain: "guineanmining.gn",
      industry: "Technology",
      hq_country: "Guinea",
      revenue: 22000000,
      employees: 280,
      technologies: ["Java", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Conakry", "Kankan", "Nzérékoré"]
    },
    {
      id: 143,
      name: "Guinea-Bissau Tech Solutions",
      domain: "guineabissautech.gw",
      industry: "Technology",
      hq_country: "Guinea-Bissau",
      revenue: 5000000,
      employees: 65,
      technologies: ["React", "Python", "MySQL", "AWS"],
      office_locations: ["Bissau", "Bafatá"]
    },
    {
      id: 144,
      name: "Sierra Leonean Diamond Tech",
      domain: "sierraleoneandiamond.sl",
      industry: "Technology",
      hq_country: "Sierra Leone",
      revenue: 12000000,
      employees: 140,
      technologies: ["Vue.js", "PHP", "MySQL", "Docker"],
      office_locations: ["Freetown", "Bo", "Kenema"]
    },
    {
      id: 145,
      name: "Liberian Maritime Solutions",
      domain: "liberianmaritime.lr",
      industry: "Logistics",
      hq_country: "Liberia",
      revenue: 18000000,
      employees: 220,
      technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
      office_locations: ["Monrovia", "Gbarnga"]
    },
    {
      id: 146,
      name: "Togolese Agricultural Platform",
      domain: "togoleseagri.tg",
      industry: "Agriculture",
      hq_country: "Togo",
      revenue: 8000000,
      employees: 110,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Lomé", "Sokodé"]
    },
    {
      id: 147,
      name: "Beninese Cotton Tech",
      domain: "beninesecotton.bj",
      industry: "Agriculture",
      hq_country: "Benin",
      revenue: 15000000,
      employees: 180,
      technologies: ["Angular", "Python", "MySQL", "IoT"],
      office_locations: ["Porto-Novo", "Cotonou", "Parakou"]
    },
    {
      id: 148,
      name: "Gambian Tourism Solutions",
      domain: "gambiantourism.gm",
      industry: "Travel",
      hq_country: "Gambia",
      revenue: 12000000,
      employees: 95,
      technologies: ["WordPress", "PHP", "MySQL", "Stripe"],
      office_locations: ["Banjul", "Serekunda"]
    },
    {
      id: 149,
      name: "Guinea-Conakry Mining Tech",
      domain: "guineaconakrymining.gn",
      industry: "Technology",
      hq_country: "Guinea",
      revenue: 25000000,
      employees: 320,
      technologies: ["Java", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Conakry", "Kankan", "Labé"]
    },
    {
      id: 150,
      name: "Mauritanian Fishing Tech",
      domain: "mauritanianfishing.mr",
      industry: "Agriculture",
      hq_country: "Mauritania",
      revenue: 18000000,
      employees: 220,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Nouakchott", "Nouadhibou"]
    },
    {
      id: 151,
      name: "Japanese AI Robotics",
      domain: "japaneseai.jp",
      industry: "Technology",
      hq_country: "Japan",
      revenue: 420000000,
      employees: 3200,
      technologies: ["Python", "TensorFlow", "ROS", "C++", "AWS"],
      office_locations: ["Tokyo", "Osaka", "Nagoya", "Fukuoka"]
    },
    {
      id: 152,
      name: "Australian Mining Analytics",
      domain: "ausmininganalytics.au",
      industry: "Technology",
      hq_country: "Australia",
      revenue: 85000000,
      employees: 650,
      technologies: ["Python", "Spark", "AWS", "PostgreSQL"],
      office_locations: ["Perth", "Adelaide", "Brisbane", "Darwin"]
    },
    {
      id: 153,
      name: "New Zealand Dairy Tech",
      domain: "nzdairytech.nz",
      industry: "Agriculture",
      hq_country: "New Zealand",
      revenue: 65000000,
      employees: 480,
      technologies: ["React", "Python", "AWS", "IoT"],
      office_locations: ["Auckland", "Wellington", "Christchurch", "Hamilton"]
    },
    {
      id: 154,
      name: "Fijian Tourism Platform",
      domain: "fijiantourism.fj",
      industry: "Travel",
      hq_country: "Fiji",
      revenue: 22000000,
      employees: 180,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Suva", "Nadi", "Lautoka"]
    },
    {
      id: 155,
      name: "Papua New Guinea Mining",
      domain: "pngmining.pg",
      industry: "Technology",
      hq_country: "Papua New Guinea",
      revenue: 38000000,
      employees: 420,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Port Moresby", "Lae", "Mount Hagen"]
    },
    {
      id: 156,
      name: "Solomon Islands Fishing Tech",
      domain: "solomonfishing.sb",
      industry: "Agriculture",
      hq_country: "Solomon Islands",
      revenue: 8000000,
      employees: 85,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Honiara", "Gizo"]
    },
    {
      id: 157,
      name: "Vanuatu Tourism Solutions",
      domain: "vanuatutourism.vu",
      industry: "Travel",
      hq_country: "Vanuatu",
      revenue: 12000000,
      employees: 95,
      technologies: ["WordPress", "PHP", "MySQL", "Stripe"],
      office_locations: ["Port Vila", "Luganville"]
    },
    {
      id: 158,
      name: "Samoan Agriculture Platform",
      domain: "samoanagri.ws",
      industry: "Agriculture",
      hq_country: "Samoa",
      revenue: 6000000,
      employees: 75,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Apia", "Salelologa"]
    },
    {
      id: 159,
      name: "Tongan Maritime Tech",
      domain: "tonganmaritime.to",
      industry: "Logistics",
      hq_country: "Tonga",
      revenue: 5000000,
      employees: 45,
      technologies: ["Vue.js", "PHP", "MySQL", "Docker"],
      office_locations: ["Nuku'alofa"]
    },
    {
      id: 160,
      name: "Kiribati Fishing Solutions",
      domain: "kiribatifishing.ki",
      industry: "Agriculture",
      hq_country: "Kiribati",
      revenue: 3000000,
      employees: 35,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Tarawa"]
    },
    {
      id: 161,
      name: "Tuvaluan Ocean Tech",
      domain: "tuvaluanocean.tv",
      industry: "Technology",
      hq_country: "Tuvalu",
      revenue: 2000000,
      employees: 25,
      technologies: ["React", "Python", "MongoDB", "AWS"],
      office_locations: ["Funafuti"]
    },
    {
      id: 162,
      name: "Nauruan Phosphate Solutions",
      domain: "nauruanphosphate.nr",
      industry: "Technology",
      hq_country: "Nauru",
      revenue: 4000000,
      employees: 38,
      technologies: ["Java", "Python", "MySQL", "Docker"],
      office_locations: ["Yaren"]
    },
    {
      id: 163,
      name: "Palauan Marine Tech",
      domain: "palauanmarine.pw",
      industry: "Technology",
      hq_country: "Palau",
      revenue: 6000000,
      employees: 55,
      technologies: ["React", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Ngerulmud", "Koror"]
    },
    {
      id: 164,
      name: "Marshallese Maritime Solutions",
      domain: "marshallmaritime.mh",
      industry: "Logistics",
      hq_country: "Marshall Islands",
      revenue: 8000000,
      employees: 85,
      technologies: ["Vue.js", "PHP", "MySQL", "Docker"],
      office_locations: ["Majuro", "Ebeye"]
    },
    {
      id: 165,
      name: "Micronesian Fishing Platform",
      domain: "micronesianfishing.fm",
      industry: "Agriculture",
      hq_country: "Micronesia",
      revenue: 5000000,
      employees: 65,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Palikir", "Weno"]
    },
    {
      id: 166,
      name: "Chilean Wine Tech",
      domain: "chileanwine.cl",
      industry: "Agriculture",
      hq_country: "Chile",
      revenue: 55000000,
      employees: 650,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Santiago", "Valparaíso", "Concepción", "La Serena"]
    },
    {
      id: 167,
      name: "Peruvian Mining Solutions",
      domain: "peruvianmining.pe",
      industry: "Technology",
      hq_country: "Peru",
      revenue: 68000000,
      employees: 780,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Lima", "Arequipa", "Trujillo", "Cusco"]
    },
    {
      id: 168,
      name: "Ecuadorian Agriculture Platform",
      domain: "ecuadorianagri.ec",
      industry: "Agriculture",
      hq_country: "Ecuador",
      revenue: 32000000,
      employees: 420,
      technologies: ["Angular", "Python", "MySQL", "IoT"],
      office_locations: ["Quito", "Guayaquil", "Cuenca"]
    },
    {
      id: 169,
      name: "Colombian Coffee Tech",
      domain: "colombiancoffee.co",
      industry: "Agriculture",
      hq_country: "Colombia",
      revenue: 45000000,
      employees: 580,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Bogotá", "Medellín", "Cali", "Barranquilla"]
    },
    {
      id: 170,
      name: "Venezuelan Oil Solutions",
      domain: "venezuelanoil.ve",
      industry: "Energy",
      hq_country: "Venezuela",
      revenue: 75000000,
      employees: 850,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Caracas", "Maracaibo", "Valencia"]
    },
    {
      id: 171,
      name: "Guyanese Gold Tech",
      domain: "guyanesegold.gy",
      industry: "Technology",
      hq_country: "Guyana",
      revenue: 18000000,
      employees: 220,
      technologies: ["Java", "Python", "MySQL", "AWS"],
      office_locations: ["Georgetown", "Linden"]
    },
    {
      id: 172,
      name: "Surinamese Bauxite Solutions",
      domain: "surinamesebauxite.sr",
      industry: "Technology",
      hq_country: "Suriname",
      revenue: 15000000,
      employees: 180,
      technologies: ["React", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Paramaribo", "Nieuw Nickerie"]
    },
    {
      id: 173,
      name: "French Guianan Space Tech",
      domain: "frenchguianspace.gf",
      industry: "Aerospace",
      hq_country: "France",
      revenue: 85000000,
      employees: 650,
      technologies: ["C++", "Python", "MATLAB", "AWS"],
      office_locations: ["Cayenne", "Kourou"]
    },
    {
      id: 174,
      name: "Uruguayan Software Solutions",
      domain: "uruguayansoft.uy",
      industry: "Technology",
      hq_country: "Uruguay",
      revenue: 28000000,
      employees: 350,
      technologies: ["React", "Node.js", "PostgreSQL", "AWS"],
      office_locations: ["Montevideo", "Salto", "Paysandú"]
    },
    {
      id: 175,
      name: "Paraguayan Agriculture Tech",
      domain: "paraguayanagri.py",
      industry: "Agriculture",
      hq_country: "Paraguay",
      revenue: 22000000,
      employees: 280,
      technologies: ["Vue.js", "Python", "MySQL", "IoT"],
      office_locations: ["Asunción", "Ciudad del Este", "San Lorenzo"]
    },
    {
      id: 176,
      name: "Bolivian Mining Platform",
      domain: "bolivianmining.bo",
      industry: "Technology",
      hq_country: "Bolivia",
      revenue: 35000000,
      employees: 450,
      technologies: ["Java", "Python", "PostgreSQL", "Docker"],
      office_locations: ["La Paz", "Santa Cruz", "Cochabamba"]
    },
    {
      id: 177,
      name: "Costa Rican Eco Tech",
      domain: "costaricanecotech.cr",
      industry: "Energy",
      hq_country: "Costa Rica",
      revenue: 38000000,
      employees: 420,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["San José", "Cartago", "Puntarenas"]
    },
    {
      id: 178,
      name: "Panamanian Logistics Hub",
      domain: "panamanianlogistics.pa",
      industry: "Logistics",
      hq_country: "Panama",
      revenue: 52000000,
      employees: 580,
      technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
      office_locations: ["Panama City", "Colón", "David"]
    },
    {
      id: 179,
      name: "Nicaraguan Agriculture Platform",
      domain: "nicaraguanagri.ni",
      industry: "Agriculture",
      hq_country: "Nicaragua",
      revenue: 18000000,
      employees: 250,
      technologies: ["Angular", "Python", "MySQL", "IoT"],
      office_locations: ["Managua", "León", "Granada"]
    },
    {
      id: 180,
      name: "Honduran Coffee Solutions",
      domain: "hondurancoffee.hn",
      industry: "Agriculture",
      hq_country: "Honduras",
      revenue: 22000000,
      employees: 320,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Tegucigalpa", "San Pedro Sula", "Choloma"]
    },
    {
      id: 181,
      name: "Salvadoran FinTech",
      domain: "salvadoranfintech.sv",
      industry: "Finance",
      hq_country: "El Salvador",
      revenue: 25000000,
      employees: 280,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["San Salvador", "Santa Ana", "San Miguel"]
    },
    {
      id: 182,
      name: "Guatemalan Agriculture Tech",
      domain: "guatemalanagri.gt",
      industry: "Agriculture",
      hq_country: "Guatemala",
      revenue: 32000000,
      employees: 420,
      technologies: ["Vue.js", "Python", "MySQL", "IoT"],
      office_locations: ["Guatemala City", "Quetzaltenango", "Escuintla"]
    },
    {
      id: 183,
      name: "Belizean Tourism Solutions",
      domain: "belizeantourism.bz",
      industry: "Travel",
      hq_country: "Belize",
      revenue: 15000000,
      employees: 120,
      technologies: ["WordPress", "PHP", "MySQL", "Stripe"],
      office_locations: ["Belmopan", "Belize City"]
    },
    {
      id: 184,
      name: "Cuban Software House",
      domain: "cubansoft.cu",
      industry: "Technology",
      hq_country: "Cuba",
      revenue: 28000000,
      employees: 380,
      technologies: ["React", "Python", "PostgreSQL", "Docker"],
      office_locations: ["Havana", "Santiago de Cuba", "Camagüey"]
    },
    {
      id: 185,
      name: "Haitian Agricultural Platform",
      domain: "haitianagri.ht",
      industry: "Agriculture",
      hq_country: "Haiti",
      revenue: 12000000,
      employees: 180,
      technologies: ["Angular", "Python", "MySQL", "IoT"],
      office_locations: ["Port-au-Prince", "Cap-Haïtien"]
    },
    {
      id: 186,
      name: "Dominican Republic Tourism",
      domain: "dominicanrepublictourism.do",
      industry: "Travel",
      hq_country: "Dominican Republic",
      revenue: 45000000,
      employees: 520,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Santo Domingo", "Santiago", "Puerto Plata"]
    },
    {
      id: 187,
      name: "Jamaican Music Tech",
      domain: "jamaicanmusic.jm",
      industry: "Media",
      hq_country: "Jamaica",
      revenue: 28000000,
      employees: 320,
      technologies: ["React", "Node.js", "AWS", "FFmpeg"],
      office_locations: ["Kingston", "Spanish Town", "Portmore"]
    },
    {
      id: 188,
      name: "Trinidadian Energy Solutions",
      domain: "trinidadianenergy.tt",
      industry: "Energy",
      hq_country: "Trinidad and Tobago",
      revenue: 65000000,
      employees: 580,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Port of Spain", "San Fernando", "Chaguanas"]
    },
    {
      id: 189,
      name: "Barbadian Tourism Platform",
      domain: "barbadiantourism.bb",
      industry: "Travel",
      hq_country: "Barbados",
      revenue: 22000000,
      employees: 180,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Bridgetown", "Speightstown"]
    },
    {
      id: 190,
      name: "Saint Lucian Resort Tech",
      domain: "saintlucianresort.lc",
      industry: "Travel",
      hq_country: "Saint Lucia",
      revenue: 18000000,
      employees: 120,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Castries", "Vieux Fort"]
    },
    {
      id: 191,
      name: "Grenadian Spice Solutions",
      domain: "grenadianspice.gd",
      industry: "Agriculture",
      hq_country: "Grenada",
      revenue: 12000000,
      employees: 95,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["St. George's", "Gouyave"]
    },
    {
      id: 192,
      name: "Saint Vincent Tech Hub",
      domain: "saintvincenttech.vc",
      industry: "Technology",
      hq_country: "Saint Vincent and the Grenadines",
      revenue: 8000000,
      employees: 75,
      technologies: ["Vue.js", "PHP", "MySQL", "AWS"],
      office_locations: ["Kingstown", "Georgetown"]
    },
    {
      id: 193,
      name: "Antiguan Tourism Solutions",
      domain: "antiguantourism.ag",
      industry: "Travel",
      hq_country: "Antigua and Barbuda",
      revenue: 15000000,
      employees: 110,
      technologies: ["WordPress", "PHP", "MySQL", "Stripe"],
      office_locations: ["St. John's", "All Saints"]
    },
    {
      id: 194,
      name: "Saint Kitts Sugar Tech",
      domain: "saintkittssugar.kn",
      industry: "Agriculture",
      hq_country: "Saint Kitts and Nevis",
      revenue: 10000000,
      employees: 85,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Basseterre", "Charlestown"]
    },
    {
      id: 195,
      name: "Dominica Nature Tech",
      domain: "dominicanature.dm",
      industry: "Technology",
      hq_country: "Dominica",
      revenue: 6000000,
      employees: 65,
      technologies: ["Angular", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Roseau", "Portsmouth"]
    },
    {
      id: 196,
      name: "Bahamian Resort Platform",
      domain: "bahamianresort.bs",
      industry: "Travel",
      hq_country: "Bahamas",
      revenue: 35000000,
      employees: 280,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Nassau", "Freeport"]
    },
    {
      id: 197,
      name: "Bermudan Insurance Tech",
      domain: "bermudaninsurance.bm",
      industry: "Finance",
      hq_country: "Bermuda",
      revenue: 95000000,
      employees: 450,
      technologies: ["Java", ".NET", "SQL Server", "Azure"],
      office_locations: ["Hamilton", "St. George's"]
    },
    {
      id: 198,
      name: "Greenlandic Ice Solutions",
      domain: "greenlandice.gl",
      industry: "Technology",
      hq_country: "Greenland",
      revenue: 12000000,
      employees: 85,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Nuuk", "Ilulissat"]
    },
    {
      id: 199,
      name: "Faroese Maritime Tech",
      domain: "faroesemaritime.fo",
      industry: "Logistics",
      hq_country: "Faroe Islands",
      revenue: 18000000,
      employees: 120,
      technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
      office_locations: ["Tórshavn", "Klaksvík"]
    },
    {
      id: 200,
      name: "Jersey Financial Solutions",
      domain: "jerseyfinancial.je",
      industry: "Finance",
      hq_country: "Jersey",
      revenue: 85000000,
      employees: 420,
      technologies: ["Java", "Spring", "PostgreSQL", "Azure"],
      office_locations: ["St. Helier", "St. Brelade"]
    },
    {
      id: 201,
      name: "Guernsey Investment Tech",
      domain: "guernseyinvestment.gg",
      industry: "Finance",
      hq_country: "Guernsey",
      revenue: 78000000,
      employees: 380,
      technologies: ["React", "TypeScript", "PostgreSQL", "AWS"],
      office_locations: ["St. Peter Port", "St. Sampson"]
    },
    {
      id: 202,
      name: "Isle of Man Gaming Solutions",
      domain: "iomgaming.im",
      industry: "Gaming",
      hq_country: "Isle of Man",
      revenue: 95000000,
      employees: 650,
      technologies: ["Unity", "C#", "PostgreSQL", "AWS"],
      office_locations: ["Douglas", "Ramsey"]
    },
    {
      id: 203,
      name: "Gibraltar FinTech Hub",
      domain: "gibraltarfintech.gi",
      industry: "Finance",
      hq_country: "Gibraltar",
      revenue: 125000000,
      employees: 580,
      technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
      office_locations: ["Gibraltar"]
    },
    {
      id: 204,
      name: "Andorran Banking Tech",
      domain: "andorranbanking.ad",
      industry: "Finance",
      hq_country: "Andorra",
      revenue: 55000000,
      employees: 280,
      technologies: ["Java", ".NET", "SQL Server", "Azure"],
      office_locations: ["Andorra la Vella", "Escaldes-Engordany"]
    },
    {
      id: 205,
      name: "Monégasque Luxury Tech",
      domain: "monegasqueluxury.mc",
      industry: "Technology",
      hq_country: "Monaco",
      revenue: 145000000,
      employees: 450,
      technologies: ["React", "Python", "AWS", "PostgreSQL"],
      office_locations: ["Monaco", "Monte Carlo"]
    },
    {
      id: 206,
      name: "San Marinese Software House",
      domain: "sanmarinesesoft.sm",
      industry: "Technology",
      hq_country: "San Marino",
      revenue: 15000000,
      employees: 120,
      technologies: ["Vue.js", "PHP", "MySQL", "Docker"],
      office_locations: ["San Marino", "Serravalle"]
    },
    {
      id: 207,
      name: "Vatican Tech Solutions",
      domain: "vaticantech.va",
      industry: "Technology",
      hq_country: "Vatican City",
      revenue: 8000000,
      employees: 45,
      technologies: ["React", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Vatican City"]
    },
    {
      id: 208,
      name: "Liechtenstein Financial Platform",
      domain: "liechtensteinfinance.li",
      industry: "Finance",
      hq_country: "Liechtenstein",
      revenue: 65000000,
      employees: 280,
      technologies: ["Java", "Spring", "PostgreSQL", "Azure"],
      office_locations: ["Vaduz", "Schaan"]
    },
    {
      id: 209,
      name: "Maltese Gaming Corporation",
      domain: "maltesegaming.mt",
      industry: "Gaming",
      hq_country: "Malta",
      revenue: 125000000,
      employees: 850,
      technologies: ["Unity", "C#", "PostgreSQL", "AWS"],
      office_locations: ["Valletta", "Sliema", "St. Julian's"]
    },
    {
      id: 210,
      name: "Cypriot Software Solutions",
      domain: "cypriotsoft.cy",
      industry: "Technology",
      hq_country: "Cyprus",
      revenue: 42000000,
      employees: 380,
      technologies: ["React", "Python", "MySQL", "AWS"],
      office_locations: ["Nicosia", "Limassol", "Larnaca"]
    },
    {
      id: 211,
      name: "Mongolian Cashmere Tech",
      domain: "mongoliancashmere.mn",
      industry: "Manufacturing",
      hq_country: "Mongolia",
      revenue: 35000000,
      employees: 420,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Ulaanbaatar", "Choibalsan", "Ölgii"]
    },
    {
      id: 212,
      name: "Tibetan Meditation App",
      domain: "tibetanmeditation.tibet",
      industry: "Healthcare",
      hq_country: "China",
      revenue: 18000000,
      employees: 150,
      technologies: ["React Native", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Lhasa", "Shigatse"]
    },
    {
      id: 213,
      name: "Hong Kong FinTech Hub",
      domain: "hkfintech.hk",
      industry: "Finance",
      hq_country: "Hong Kong",
      revenue: 185000000,
      employees: 1200,
      technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
      office_locations: ["Central", "Tsim Sha Tsui", "Causeway Bay"]
    },
    {
      id: 214,
      name: "Macau Gaming Platform",
      domain: "macaugaming.mo",
      industry: "Gaming",
      hq_country: "Macau",
      revenue: 220000000,
      employees: 1450,
      technologies: ["Unity", "C#", "PostgreSQL", "AWS"],
      office_locations: ["Macau Peninsula", "Taipa", "Coloane"]
    },
    {
      id: 215,
      name: "Taiwanese Semiconductor Tech",
      domain: "taiwansemiconductor.tw",
      industry: "Technology",
      hq_country: "Taiwan",
      revenue: 520000000,
      employees: 4200,
      technologies: ["C++", "Python", "MATLAB", "FPGA"],
      office_locations: ["Taipei", "Taichung", "Kaohsiung", "Hsinchu"]
    },
    {
      id: 216,
      name: "Bruneian Islamic Banking",
      domain: "bruneiislamic.bn",
      industry: "Finance",
      hq_country: "Brunei",
      revenue: 68000000,
      employees: 420,
      technologies: ["Java", "Spring", "PostgreSQL", "Azure"],
      office_locations: ["Bandar Seri Begawan", "Seria"]
    },
    {
      id: 217,
      name: "Timorese Coffee Platform",
      domain: "timoresecoffee.tl",
      industry: "Agriculture",
      hq_country: "East Timor",
      revenue: 8000000,
      employees: 95,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Dili", "Baucau"]
    },
    {
      id: 218,
      name: "Bhutanese Hydropower Tech",
      domain: "bhutanesehydro.bt",
      industry: "Energy",
      hq_country: "Bhutan",
      revenue: 45000000,
      employees: 320,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Thimphu", "Paro", "Punakha"]
    },
    {
      id: 219,
      name: "Indian IT Outsourcing Giant",
      domain: "indianitoutsourcing.in",
      industry: "Technology",
      hq_country: "India",
      revenue: 650000000,
      employees: 8500,
      technologies: ["Java", "Python", "AWS", "Kubernetes", "React"],
      office_locations: ["Hyderabad", "Pune", "Noida", "Gurgaon", "Kolkata"]
    },
    {
      id: 220,
      name: "Myanmarese Jade Solutions",
      domain: "myanmaresejade.mm",
      industry: "Technology",
      hq_country: "Myanmar",
      revenue: 28000000,
      employees: 350,
      technologies: ["React", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Yangon", "Mandalay", "Naypyidaw"]
    },
    {
      id: 221,
      name: "Laotian Hydropower Tech",
      domain: "laotianhydro.la",
      industry: "Energy",
      hq_country: "Laos",
      revenue: 35000000,
      employees: 280,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Vientiane", "Pakse", "Savannakhet"]
    },
    {
      id: 222,
      name: "Cambodian Tourism Solutions",
      domain: "cambodiantourism.kh",
      industry: "Travel",
      hq_country: "Cambodia",
      revenue: 42000000,
      employees: 480,
      technologies: ["Vue.js", "PHP", "MySQL", "Stripe"],
      office_locations: ["Phnom Penh", "Siem Reap", "Sihanoukville"]
    },
    {
      id: 223,
      name: "Vietnamese Electronics Manufacturing",
      domain: "vietnameseelectronics.vn",
      industry: "Manufacturing",
      hq_country: "Vietnam",
      revenue: 320000000,
      employees: 2800,
      technologies: ["C++", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Ho Chi Minh City", "Hanoi", "Hai Phong", "Can Tho"]
    },
    {
      id: 224,
      name: "Philippine Call Center Tech",
      domain: "philippinecallcenter.ph",
      industry: "Technology",
      hq_country: "Philippines",
      revenue: 125000000,
      employees: 3200,
      technologies: ["React", "Node.js", "AWS", "WebRTC"],
      office_locations: ["Manila", "Cebu City", "Davao City", "Iloilo City"]
    },
    {
      id: 225,
      name: "Indonesian Palm Oil Tech",
      domain: "indonesianpalmoil.id",
      industry: "Agriculture",
      hq_country: "Indonesia",
      revenue: 180000000,
      employees: 1850,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Jakarta", "Medan", "Palembang", "Pontianak"]
    },
    {
      id: 226,
      name: "Malaysian Rubber Solutions",
      domain: "malaysianrubber.my",
      industry: "Agriculture",
      hq_country: "Malaysia",
      revenue: 95000000,
      employees: 1100,
      technologies: ["Angular", "Python", "MySQL", "IoT"],
      office_locations: ["Kuala Lumpur", "Ipoh", "Johor Bahru", "Kuching"]
    },
    {
      id: 227,
      name: "Chinese Manufacturing Hub",
      domain: "chinesemanufacturing.cn",
      industry: "Manufacturing",
      hq_country: "China",
      revenue: 1200000000,
      employees: 15000,
      technologies: ["Java", "Python", "PostgreSQL", "IoT", "AI"],
      office_locations: ["Shenzhen", "Guangzhou", "Dongguan", "Foshan", "Zhongshan"]
    },
    {
      id: 228,
      name: "South Korean Electronics",
      domain: "koreanelectronics.kr",
      industry: "Manufacturing",
      hq_country: "South Korea",
      revenue: 850000000,
      employees: 12000,
      technologies: ["C++", "Python", "PostgreSQL", "IoT", "5G"],
      office_locations: ["Seoul", "Suwon", "Daegu", "Busan", "Incheon"]
    },
    {
      id: 229,
      name: "Japanese Automotive Tech",
      domain: "japaneseautomotive.jp",
      industry: "Manufacturing",
      hq_country: "Japan",
      revenue: 2200000000,
      employees: 28000,
      technologies: ["C++", "Python", "MATLAB", "CAN Bus", "LiDAR"],
      office_locations: ["Tokyo", "Nagoya", "Hiroshima", "Sendai", "Sapporo"]
    },
    {
      id: 230,
      name: "Australian Wine Tech",
      domain: "australianwine.au",
      industry: "Agriculture",
      hq_country: "Australia",
      revenue: 125000000,
      employees: 950,
      technologies: ["React", "Python", "AWS", "IoT"],
      office_locations: ["Adelaide", "Melbourne", "Perth", "Hobart"]
    },
    {
      id: 231,
      name: "New Zealand Tech Innovation",
      domain: "nztechinnovation.nz",
      industry: "Technology",
      hq_country: "New Zealand",
      revenue: 95000000,
      employees: 680,
      technologies: ["React", "TypeScript", "AWS", "PostgreSQL"],
      office_locations: ["Auckland", "Wellington", "Christchurch", "Dunedin"]
    },
    {
      id: 232,
      name: "Canadian Maple Syrup Tech",
      domain: "canadianmaplesyrup.ca",
      industry: "Agriculture",
      hq_country: "Canada",
      revenue: 45000000,
      employees: 380,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Montreal", "Quebec City", "Ottawa", "Halifax"]
    },
    {
      id: 233,
      name: "US Silicon Valley AI",
      domain: "usai.com",
      industry: "Technology",
      hq_country: "USA",
      revenue: 2800000000,
      employees: 18000,
      technologies: ["Python", "TensorFlow", "PyTorch", "Kubernetes", "AWS"],
      office_locations: ["San Francisco", "Mountain View", "Palo Alto", "Cupertino", "San Jose"]
    },
    {
      id: 234,
      name: "Mexican Automotive Solutions",
      domain: "mexicanautomotive.mx",
      industry: "Manufacturing",
      hq_country: "Mexico",
      revenue: 380000000,
      employees: 4200,
      technologies: ["C++", "Java", "PostgreSQL", "IoT"],
      office_locations: ["Mexico City", "Tijuana", "Puebla", "León"]
    },
    {
      id: 235,
      name: "Guatemalan Textile Tech",
      domain: "guatemalantextile.gt",
      industry: "Manufacturing",
      hq_country: "Guatemala",
      revenue: 55000000,
      employees: 850,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Guatemala City", "Quetzaltenango", "Villa Nueva"]
    },
    {
      id: 236,
      name: "Colombian Emerald Solutions",
      domain: "colombianemerald.co",
      industry: "Technology",
      hq_country: "Colombia",
      revenue: 68000000,
      employees: 520,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Bogotá", "Medellín", "Cartagena", "Bucaramanga"]
    },
    {
      id: 237,
      name: "Brazilian Aerospace Tech",
      domain: "brazilianaerospace.br",
      industry: "Aerospace",
      hq_country: "Brazil",
      revenue: 450000000,
      employees: 3800,
      technologies: ["C++", "Python", "MATLAB", "FPGA"],
      office_locations: ["São José dos Campos", "São Paulo", "Rio de Janeiro", "Brasília"]
    },
    {
      id: 238,
      name: "Argentinian Beef Tech",
      domain: "argentinianbeef.ar",
      industry: "Agriculture",
      hq_country: "Argentina",
      revenue: 85000000,
      employees: 750,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"]
    },
    {
      id: 239,
      name: "Chilean Copper Mining Tech",
      domain: "chileancopper.cl",
      industry: "Technology",
      hq_country: "Chile",
      revenue: 320000000,
      employees: 2800,
      technologies: ["Java", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Santiago", "Antofagasta", "Calama", "Copiapó"]
    },
    {
      id: 240,
      name: "Uruguayan Beef Solutions",
      domain: "uruguayanbeef.uy",
      industry: "Agriculture",
      hq_country: "Uruguay",
      revenue: 42000000,
      employees: 380,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Montevideo", "Punta del Este", "Rivera"]
    },
    {
      id: 241,
      name: "Paraguayan Soybean Tech",
      domain: "paraguayansoybean.py",
      industry: "Agriculture",
      hq_country: "Paraguay",
      revenue: 35000000,
      employees: 420,
      technologies: ["Vue.js", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Asunción", "Ciudad del Este", "Encarnación"]
    },
    {
      id: 242,
      name: "Bolivian Lithium Solutions",
      domain: "bolivianlithium.bo",
      industry: "Technology",
      hq_country: "Bolivia",
      revenue: 95000000,
      employees: 850,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["La Paz", "Santa Cruz", "Potosí", "Oruro"]
    },
    {
      id: 243,
      name: "Peruvian Quinoa Tech",
      domain: "peruvianquinoa.pe",
      industry: "Agriculture",
      hq_country: "Peru",
      revenue: 28000000,
      employees: 320,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Lima", "Cusco", "Puno", "Huancayo"]
    },
    {
      id: 244,
      name: "Ecuadorian Banana Platform",
      domain: "ecuadorianbanana.ec",
      industry: "Agriculture",
      hq_country: "Ecuador",
      revenue: 65000000,
      employees: 780,
      technologies: ["Angular", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Quito", "Guayaquil", "Machala", "Milagro"]
    },
    {
      id: 245,
      name: "Venezuelan Cryptocurrency",
      domain: "venezuelancrypto.ve",
      industry: "Finance",
      hq_country: "Venezuela",
      revenue: 45000000,
      employees: 380,
      technologies: ["React", "Node.js", "MongoDB", "Blockchain"],
      office_locations: ["Caracas", "Valencia", "Barquisimeto"]
    },
    {
      id: 246,
      name: "Guyanese Sugar Solutions",
      domain: "guyanesesugar.gy",
      industry: "Agriculture",
      hq_country: "Guyana",
      revenue: 22000000,
      employees: 280,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Georgetown", "New Amsterdam"]
    },
    {
      id: 247,
      name: "Surinamese Rice Tech",
      domain: "surinameserice.sr",
      industry: "Agriculture",
      hq_country: "Suriname",
      revenue: 18000000,
      employees: 220,
      technologies: ["Vue.js", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Paramaribo", "Lelydorp"]
    },
    {
      id: 248,
      name: "African Union Tech Hub",
      domain: "africanuniontech.africa",
      industry: "Technology",
      hq_country: "Ethiopia",
      revenue: 125000000,
      employees: 980,
      technologies: ["React", "Python", "AWS", "Kubernetes"],
      office_locations: ["Addis Ababa", "Cairo", "Lagos", "Nairobi"]
    },
    {
      id: 249,
      name: "Moroccan Argan Oil Tech",
      domain: "moroccanoil.ma",
      industry: "Agriculture",
      hq_country: "Morocco",
      revenue: 48000000,
      employees: 520,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Casablanca", "Agadir", "Essaouira", "Marrakech"]
    },
    {
      id: 250,
      name: "Algerian Gas Solutions",
      domain: "algeriangas.dz",
      industry: "Energy",
      hq_country: "Algeria",
      revenue: 185000000,
      employees: 1650,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Algiers", "Oran", "Hassi Messaoud", "In Amenas"]
    },
    {
      id: 251,
      name: "Tunisian Olive Oil Platform",
      domain: "tunisianoil.tn",
      industry: "Agriculture",
      hq_country: "Tunisia",
      revenue: 35000000,
      employees: 420,
      technologies: ["Angular", "Python", "MySQL", "IoT"],
      office_locations: ["Tunis", "Sfax", "Kairouan", "Monastir"]
    },
    {
      id: 252,
      name: "Libyan Reconstruction Tech",
      domain: "libyanreconstruction.ly",
      industry: "Technology",
      hq_country: "Libya",
      revenue: 85000000,
      employees: 780,
      technologies: ["React", "Python", "AWS", "PostgreSQL"],
      office_locations: ["Tripoli", "Benghazi", "Misrata", "Bayda"]
    },
    {
      id: 253,
      name: "Egyptian Pyramid VR",
      domain: "egyptianpyramidvr.eg",
      industry: "Technology",
      hq_country: "Egypt",
      revenue: 65000000,
      employees: 580,
      technologies: ["Unity", "C#", "AWS", "VR/AR"],
      office_locations: ["Cairo", "Alexandria", "Giza", "Aswan"]
    },
    {
      id: 254,
      name: "Sudanese Gum Arabic Tech",
      domain: "sudanesegumarabic.sd",
      industry: "Agriculture",
      hq_country: "Sudan",
      revenue: 28000000,
      employees: 380,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Khartoum", "Kassala", "El Obeid"]
    },
    {
      id: 255,
      name: "South Sudanese Infrastructure",
      domain: "southsudaninfra.ss",
      industry: "Technology",
      hq_country: "South Sudan",
      revenue: 45000000,
      employees: 520,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Juba", "Bentiu", "Bor"]
    },
    {
      id: 256,
      name: "Ethiopian Coffee Platform",
      domain: "ethiopiancoffee.et",
      industry: "Agriculture",
      hq_country: "Ethiopia",
      revenue: 85000000,
      employees: 980,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Addis Ababa", "Jimma", "Harar", "Sidama"]
    },
    {
      id: 257,
      name: "Eritrean Potash Solutions",
      domain: "eritreanpotash.er",
      industry: "Technology",
      hq_country: "Eritrea",
      revenue: 22000000,
      employees: 280,
      technologies: ["Java", "Python", "MySQL", "IoT"],
      office_locations: ["Asmara", "Massawa", "Keren"]
    },
    {
      id: 258,
      name: "Djiboutian Port Tech",
      domain: "djiboutianport.dj",
      industry: "Logistics",
      hq_country: "Djibouti",
      revenue: 95000000,
      employees: 750,
      technologies: ["React", "Node.js", "PostgreSQL", "IoT"],
      office_locations: ["Djibouti City", "Tadjourah"]
    },
    {
      id: 259,
      name: "Somali Livestock Solutions",
      domain: "somalilivestock.so",
      industry: "Agriculture",
      hq_country: "Somalia",
      revenue: 18000000,
      employees: 250,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Mogadishu", "Hargeisa", "Garowe"]
    },
    {
      id: 260,
      name: "Kenyan Safari Tech",
      domain: "kenyansafari.ke",
      industry: "Travel",
      hq_country: "Kenya",
      revenue: 78000000,
      employees: 650,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Nairobi", "Mombasa", "Nakuru", "Eldoret"]
    },
    {
      id: 261,
      name: "Ugandan Coffee Platform",
      domain: "ugandancoffee.ug",
      industry: "Agriculture",
      hq_country: "Uganda",
      revenue: 35000000,
      employees: 420,
      technologies: ["Vue.js", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Kampala", "Entebbe", "Jinja", "Mbarara"]
    },
    {
      id: 262,
      name: "Rwandan Tech Innovation Hub",
      domain: "rwandantechhub.rw",
      industry: "Technology",
      hq_country: "Rwanda",
      revenue: 65000000,
      employees: 580,
      technologies: ["React", "Python", "AWS", "AI"],
      office_locations: ["Kigali", "Muhanga", "Huye"]
    },
    {
      id: 263,
      name: "Burundian Tea Solutions",
      domain: "burundiantea.bi",
      industry: "Agriculture",
      hq_country: "Burundi",
      revenue: 12000000,
      employees: 180,
      technologies: ["React", "PHP", "MySQL", "IoT"],
      office_locations: ["Gitega", "Bujumbura", "Muyinga"]
    },
    {
      id: 264,
      name: "Tanzanian Gold Tech",
      domain: "tanzaniangold.tz",
      industry: "Technology",
      hq_country: "Tanzania",
      revenue: 125000000,
      employees: 1100,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Dar es Salaam", "Mwanza", "Dodoma", "Mbeya"]
    },
    {
      id: 265,
      name: "Congolese Cobalt Platform",
      domain: "congolesecobalt.cd",
      industry: "Technology",
      hq_country: "Democratic Republic of Congo",
      revenue: 220000000,
      employees: 1850,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Kinshasa", "Lubumbashi", "Kolwezi", "Likasi"]
    },
    {
      id: 266,
      name: "Central African Diamond Tech",
      domain: "centralafrican.cf",
      industry: "Technology",
      hq_country: "Central African Republic",
      revenue: 15000000,
      employees: 150,
      technologies: ["React", "Python", "MySQL", "Docker"],
      office_locations: ["Bangui", "Bouar"]
    },
    {
      id: 267,
      name: "Cameroonian Cocoa Solutions",
      domain: "camerooniancocoa.cm",
      industry: "Agriculture",
      hq_country: "Cameroon",
      revenue: 65000000,
      employees: 780,
      technologies: ["Angular", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Yaoundé", "Douala", "Bafoussam", "Garoua"]
    },
    {
      id: 268,
      name: "Equatorial Guinea Oil Platform",
      domain: "equatorialguineaoil.gq",
      industry: "Energy",
      hq_country: "Equatorial Guinea",
      revenue: 185000000,
      employees: 980,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Malabo", "Bata", "Mongomo"]
    },
    {
      id: 269,
      name: "Gabonese Manganese Tech",
      domain: "gabonesemanganese.ga",
      industry: "Technology",
      hq_country: "Gabon",
      revenue: 85000000,
      employees: 650,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Libreville", "Port-Gentil", "Franceville", "Oyem"]
    },
    {
      id: 270,
      name: "Republic of Congo Timber",
      domain: "congotimber.cg",
      industry: "Agriculture",
      hq_country: "Republic of Congo",
      revenue: 32000000,
      employees: 420,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Brazzaville", "Pointe-Noire", "Dolisie"]
    },
    {
      id: 271,
      name: "Angolan Oil Tech Giant",
      domain: "angolanoilgiant.ao",
      industry: "Energy",
      hq_country: "Angola",
      revenue: 520000000,
      employees: 4200,
      technologies: ["Python", "IoT", "Azure", "PostgreSQL"],
      office_locations: ["Luanda", "Cabinda", "Soyo", "Malongo"]
    },
    {
      id: 272,
      name: "Zambian Emerald Solutions",
      domain: "zambianemerald.zm",
      industry: "Technology",
      hq_country: "Zambia",
      revenue: 45000000,
      employees: 480,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Lusaka", "Kitwe", "Ndola", "Solwezi"]
    },
    {
      id: 273,
      name: "Zimbabwean Tobacco Tech",
      domain: "zimbabweantobacco.zw",
      industry: "Agriculture",
      hq_country: "Zimbabwe",
      revenue: 28000000,
      employees: 380,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Harare", "Bulawayo", "Chinhoyi", "Karoi"]
    },
    {
      id: 274,
      name: "Botswanan Beef Platform",
      domain: "botswananbeef.bw",
      industry: "Agriculture",
      hq_country: "Botswana",
      revenue: 55000000,
      employees: 520,
      technologies: ["Angular", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Gaborone", "Francistown", "Maun", "Lobatse"]
    },
    {
      id: 275,
      name: "Namibian Uranium Tech",
      domain: "namibianuranium.na",
      industry: "Energy",
      hq_country: "Namibia",
      revenue: 185000000,
      employees: 1200,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Windhoek", "Swakopmund", "Walvis Bay", "Rössing"]
    },
    {
      id: 276,
      name: "Swazi Sugar Solutions",
      domain: "swazisugar.sz",
      industry: "Agriculture",
      hq_country: "Eswatini",
      revenue: 35000000,
      employees: 450,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Mbabane", "Manzini", "Big Bend"]
    },
    {
      id: 277,
      name: "Lesotho Water Tech",
      domain: "lesothowater.ls",
      industry: "Technology",
      hq_country: "Lesotho",
      revenue: 22000000,
      employees: 250,
      technologies: ["Java", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Maseru", "Hlotse", "Mafeteng"]
    },
    {
      id: 278,
      name: "Malawian Tobacco Platform",
      domain: "malawiantobacco.mw",
      industry: "Agriculture",
      hq_country: "Malawi",
      revenue: 42000000,
      employees: 580,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Lilongwe", "Blantyre", "Zomba", "Kasungu"]
    },
    {
      id: 279,
      name: "Mozambican Cashew Tech",
      domain: "mozambicancashew.mz",
      industry: "Agriculture",
      hq_country: "Mozambique",
      revenue: 28000000,
      employees: 380,
      technologies: ["Vue.js", "Python", "MySQL", "IoT"],
      office_locations: ["Maputo", "Nampula", "Nacala", "Pemba"]
    },
    {
      id: 280,
      name: "Madagascan Sapphire Solutions",
      domain: "madagascansapphire.mg",
      industry: "Technology",
      hq_country: "Madagascar",
      revenue: 65000000,
      employees: 580,
      technologies: ["Java", "Python", "PostgreSQL", "AWS"],
      office_locations: ["Antananarivo", "Antsirabe", "Ilakaka", "Sakaraha"]
    },
    {
      id: 281,
      name: "Mauritian Textile Platform",
      domain: "mauritiantextile.mu",
      industry: "Manufacturing",
      hq_country: "Mauritius",
      revenue: 85000000,
      employees: 1200,
      technologies: ["React", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Port Louis", "Curepipe", "Vacoas-Phoenix"]
    },
    {
      id: 282,
      name: "Seychellois Fishing Tech",
      domain: "seychelloisfishing.sc",
      industry: "Agriculture",
      hq_country: "Seychelles",
      revenue: 32000000,
      employees: 220,
      technologies: ["React", "Python", "MySQL", "IoT"],
      office_locations: ["Victoria", "Baie Sainte Anne"]
    },
    {
      id: 283,
      name: "Comorian Vanilla Solutions",
      domain: "comorianvanilla.km",
      industry: "Agriculture",
      hq_country: "Comoros",
      revenue: 15000000,
      employees: 150,
      technologies: ["Vue.js", "PHP", "MySQL", "IoT"],
      office_locations: ["Moroni", "Fomboni", "Domoni"]
    },
    {
      id: 284,
      name: "Cape Verdean Tourism Tech",
      domain: "capeverdeantourism.cv",
      industry: "Travel",
      hq_country: "Cape Verde",
      revenue: 28000000,
      employees: 280,
      technologies: ["React", "Node.js", "MongoDB", "Stripe"],
      office_locations: ["Praia", "Mindelo", "Santa Maria"]
    },
    {
      id: 285,
      name: "Guinean Bauxite Platform",
      domain: "guineanbauxite.gn",
      industry: "Technology",
      hq_country: "Guinea",
      revenue: 185000000,
      employees: 1450,
      technologies: ["Python", "IoT", "AWS", "PostgreSQL"],
      office_locations: ["Conakry", "Boké", "Kamsar", "Sangarédi"]
    },
    {
      id: 286,
      name: "Sierra Leonean Iron Ore Tech",
      domain: "sierraleoneanironore.sl",
      industry: "Technology",
      hq_country: "Sierra Leone",
      revenue: 125000000,
      employees: 980,
      technologies: ["Java", "Python", "PostgreSQL", "IoT"],
      office_locations: ["Freetown", "Bo", "Makeni", "Kenema"]
    },
    
];

export const allTechnologies = [...new Set(companies.flatMap(c => c.technologies))].sort();
export const allIndustries = [...new Set(companies.map(c => c.industry))].sort();
export const allCountries = [...new Set(companies.map(c => c.hq_country))].sort();
export const allOfficeLocations = [...new Set(companies.flatMap(c => c.office_locations))].sort();
